# Generated by Django 5.2 on 2025-04-07 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_inventoryitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quantity_before', models.IntegerField(blank=True, null=True)),
                ('quantity_after', models.IntegerField(blank=True, null=True)),
                ('low_stock_before', models.BooleanField(blank=True, null=True)),
                ('low_stock_after', models.BooleanField(blank=True, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='api.inventoryitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
